"""add_actors_and_genres_tables

Revision ID: 4f673c4ded31
Revises: 48e28df98afc
Create Date: 2025-02-17 03:01:10.475071+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f673c4ded31'
down_revision: Union[str, None] = '48e28df98afc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actors',
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('tmdb_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('actor_id'),
    sa.UniqueConstraint('tmdb_id')
    )
    op.create_table('user_preferred_genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('genre', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_preferred_genres')
    op.drop_table('actors')
    # ### end Alembic commands ###
